### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by jahentao** [liangrui1988/java-admin#2]
我checkout 的Tag: v500
登录界面，输入admin admiin，跳出提示框，并没有登录

[登录问题](http://images-markdown.oss-cn-hangzhou.aliyuncs.com/configure/github/liangrui1988/java-admin/java-admin.png)

**Comment by jahentao** [comment]
checkout 的Tag: v400
登录界面，输入admin admiin，是可以登录的

**Comment by liangrui1988** [comment]
谢谢！这个是我没注意改SimpleMain.java的参数，请运行AdminMain.java来启动，然后http://localhost:9899/zdata/来登录。
master上已经改了正确参数
